version: '3.8'

services:
  nginx-server:
    image: "nginx:stable-alpine"
    # expose:
    #   - 80
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-server
      - mysql-server

  php-server:
    build: 
      context: "./dockerfiles"
      dockerfile: "php.Dockerfile"
    volumes:
      - ./src:/var/www/html

  mysql-server:
    platform: linux/x86_64
    image: "mysql:5.7"
    env_file:
      - "./env/mysql.env"


  composer-server:
    build: 
      context: "./dockerfiles"
      dockerfile: "composer.Dockerfile"
    volumes:
      - ./src:/var/www/html









## Making the laravel project
# docker-compose run --rm composer-server create-project --prefer-dist laravel/laravel .


##Running the laravel project
# docker-compose up -d --build nginx-server