version: '3.8'

services:
  nginx-server:
    image: "nginx:stable-alpine"
    # expose:
    #   - 80
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  php-server:
    build: 
      context: "./dockerfiles"
      dockerfile: "php.Dockerfile"
    volumes:
      - ./src:/var/www/html

  mysql-server:
    image: "mysql:5.7"
    env_file:
      - "./env/mysql.env"


  composer-server:
    build: 
      context: "./dockerfiles"
      dockerfile: "composer.Dockerfile"
    volumes:
      - ./src:/var/www/html